max_email_length: 255
min_password_length: 6
max_user_name_length: 255
max_show_name_length: 255
max_room_name_length: 255
min_show_name_length: 6
min_room_name_length: 6
min_description_length: 15
rooms_per_page: 5
